### ISSUE TITLE
GameBox START_GAME error - Paper 1.12.2

### ISSUE THREAD

**Issue by andris155** [NiklasEi/gamebox#33]
```
15:45:14] [Server thread/INFO]: Fox_Pixel issued server command: /gb
[15:45:16] [Server thread/ERROR]: [GameBox] Caught java.lang.NullPointerException
[15:45:16] [Server thread/ERROR]: [GameBox]   Action: START_GAME
[15:45:16] [Server thread/ERROR]: [GameBox]   Args: [cookieclicker, weekly]
[15:45:16] [Server thread/WARN]: java.lang.NullPointerException
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.games.cookieclicker.CCGame.updateOven(CCGame.java:152)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.games.cookieclicker.CCGame.load(CCGame.java:372)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.games.cookieclicker.CCGame.access$000(CCGame.java:37)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.games.cookieclicker.CCGame$1.onSuccess(CCGame.java:97)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.games.cookieclicker.CCGame$1.onSuccess(CCGame.java:94)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.games.cookieclicker.data.FileDatabase.getGameSave(FileDatabase.java:73)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.games.cookieclicker.CCGame.<init>(CCGame.java:94)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.games.cookieclicker.CCGameManager.startGame(CCGameManager.java:76)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.inventory.gui.AGui.action(AGui.java:157)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.inventory.gui.AGui.onInventoryClick(AGui.java:409)
[15:45:16] [Server thread/WARN]: 	at me.nikl.gamebox.PluginManager.onInvClick(PluginManager.java:292)
[15:45:16] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor413.execute(Unknown Source)
[15:45:16] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[15:45:16] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[15:45:16] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:45:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[15:45:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[15:45:16] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:45:16] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[15:45:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[15:45:16] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by NiklasEi** [comment]
Updated GameBox at the same time when you opened this issue :)
