### ISSUE TITLE
TopListPage update error - Paper 1.12.2

### ISSUE THREAD

**Issue by andris155** [NiklasEi/gamebox#34]
```
[12:07:26] [Server thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@69409f43[id=4ad91db2-c289-4381-b112-6118dae49d68,name=andris155,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.12.2.jar:git-Paper-1414]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [patched_1.12.2.jar:git-Paper-1414]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [patched_1.12.2.jar:git-Paper-1414]
	at com.destroystokyo.paper.profile.WrappedMinecraftSessionService.fillProfileProperties(WrappedMinecraftSessionService.java:67) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:79) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:46) [patched_1.12.2.jar:git-Paper-1414]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [patched_1.12.2.jar:git-Paper-1414]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [patched_1.12.2.jar:git-Paper-1414]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [patched_1.12.2.jar:git-Paper-1414]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [patched_1.12.2.jar:git-Paper-1414]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [patched_1.12.2.jar:git-Paper-1414]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [patched_1.12.2.jar:git-Paper-1414]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [patched_1.12.2.jar:git-Paper-1414]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:206) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:203) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.TileEntitySkull.b(TileEntitySkull.java:222) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:86) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:385) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:46) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96) [patched_1.12.2.jar:git-Paper-1414]
	at me.nikl.gamebox.utility.ItemStackUtility.getPlayerHead(ItemStackUtility.java:109) [GameBox.jar:?]
	at me.nikl.gamebox.inventory.gui.game.TopListPage.update(TopListPage.java:69) [GameBox.jar:?]
	at me.nikl.gamebox.data.toplist.TopList.updateUsers(TopList.java:70) [GameBox.jar:?]
	at me.nikl.gamebox.data.toplist.TopList.updatePlayerScores(TopList.java:42) [GameBox.jar:?]
	at me.nikl.gamebox.data.database.FileDB$2.onSuccess(FileDB.java:139) [GameBox.jar:?]
	at me.nikl.gamebox.data.database.FileDB$2.onSuccess(FileDB.java:136) [GameBox.jar:?]
	at me.nikl.gamebox.data.database.FileDB$3$1.run(FileDB.java:254) [GameBox.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1414]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by Matocolotoe** [comment]
I also have this error on every server start but it doesn't crash
Spigot : 1.8.8

**Comment by NiklasEi** [comment]
I am closing this issue in favour of #56, since this is a general problem with player heads and top lists in GameBox.
