### ISSUE TITLE
Not work - Java 10

### ISSUE THREAD

**Issue by andris155** [NiklasEi/gamebox#35]
```
[16:56:28] [Server thread/INFO]: [GameBox] Enabling GameBox v2.1.1
[16:56:28] [Server thread/INFO]: [GameBox] [ACF] Minecraft Version: 1.12
[16:56:28] [Server thread/ERROR]: Error occurred while enabling GameBox v2.1.1 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class me/nikl/gamebox/common/acf/RootCommand. Method lambda$addChildShared$0(Lcom/google/common/collect/SetMultimap;Lme/nikl/gamebox/common/acf/BaseCommand;Ljava/util/Map$Entry;)V at index 55 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at me.nikl.gamebox.common.acf.RootCommand.addChildShared(RootCommand.java:45) ~[?:?]
	at me.nikl.gamebox.common.acf.BukkitRootCommand.addChild(BukkitRootCommand.java:74) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.register(BaseCommand.java:285) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.registerSubcommand(BaseCommand.java:317) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.registerSubcommands(BaseCommand.java:254) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.onRegister(BaseCommand.java:145) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.onRegister(BaseCommand.java:124) ~[?:?]
	at me.nikl.gamebox.common.acf.BukkitCommandManager.registerCommand(BukkitCommandManager.java:184) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.registerCommand(GameBoxCommands.java:64) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.registerCommands(GameBoxCommands.java:44) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.<init>(GameBoxCommands.java:40) ~[?:?]
	at me.nikl.gamebox.GameBox.reload(GameBox.java:215) ~[?:?]
	at me.nikl.gamebox.GameBox.onEnable(GameBox.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1414]
	at java.lang.Thread.run(Unknown Source) [?:?]
[16:56:28] [Server thread/INFO]: [GameBox] Disabling GameBox v2.1.1
```

**Comment by NiklasEi** [comment]
This comes from the command framework [ACF](https://github.com/aikar/commands) by Aikar. You could try passing this on to him.

**Comment by NiklasEi** [comment]
See aikar/commands#129
