### ISSUE TITLE
enabling GameBox on Spigot 1.12.2 Java 9.0.4

### ISSUE THREAD

**Issue by Daxtabold** [NiklasEi/gamebox#36]
Thank you for your effort, its still dont work. 
Here my full Setup and Log.

OS: Windows Server 2016
Java: 9.04 64x

I deleted all GameBox Folders and jar's n the Plugin folder, restarted the server many times.

Here the Screenshot from my Plugin Jar's
https://i.imgur.com/HwPYHRJ.jpg

`[10:50:43] [Server thread/INFO]: [GameBox] Enabling GameBox v2.1.2
[10:50:44] [Server thread/INFO]: [ACF] Minecraft Version: 1.12
[10:50:44] [Server thread/ERROR]: Error occurred while enabling GameBox v2.1.2 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class me/nikl/gamebox/common/acf/RootCommand. Method lambda$addChildShared$0(Lcom/google/common/collect/SetMultimap;Lme/nikl/gamebox/common/acf/BaseCommand;Ljava/util/Map$Entry;)V at index 55 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at me.nikl.gamebox.common.acf.RootCommand.addChildShared(RootCommand.java:45) ~[?:?]
	at me.nikl.gamebox.common.acf.BukkitRootCommand.addChild(BukkitRootCommand.java:74) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.register(BaseCommand.java:285) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.registerSubcommand(BaseCommand.java:317) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.registerSubcommands(BaseCommand.java:254) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.onRegister(BaseCommand.java:145) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.onRegister(BaseCommand.java:124) ~[?:?]
	at me.nikl.gamebox.common.acf.BukkitCommandManager.registerCommand(BukkitCommandManager.java:184) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.registerCommand(GameBoxCommands.java:64) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.registerCommands(GameBoxCommands.java:44) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.<init>(GameBoxCommands.java:40) ~[?:?]
	at me.nikl.gamebox.GameBox.reload(GameBox.java:215) ~[?:?]
	at me.nikl.gamebox.GameBox.onEnable(GameBox.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Unknown Source) [?:?]
[10:50:44] [Server thread/INFO]: [Battleship] Enabling Battleship v3.0.0
[10:50:44] [Server thread/ERROR]: Error occurred while enabling Battleship v3.0.0 (Is it up to date?)
java.lang.NullPointerException: null
	at me.nikl.gamebox.GameRegistry.handleModuleSettings(GameRegistry.java:109) ~[?:?]
	at me.nikl.gamebox.GameRegistry.registerModule(GameRegistry.java:91) ~[?:?]
	at me.nikl.gamebox.Module.<init>(Module.java:30) ~[?:?]
	at me.nikl.gamebox.games.BattleshipPlugin.onEnable(BattleshipPlugin.java:22) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Unknown Source) [?:?]`

**Comment by Daxtabold** [comment]
[latest.log](https://github.com/NiklasEi/gamebox/files/2086795/latest.log)

**Comment by NiklasEi** [comment]
Error occurred while enabling GameBox v2.1.2 (Is it up to date?)

This is still the old version. The fix was done in 2.1.3.

**Comment by Daxtabold** [comment]
No, i use the new version. It only shows 2.1.2

**Comment by Daxtabold** [comment]
![2018-06-09 11_30_46-46 38 234 212 - remotedesktopverbindung](https://user-images.githubusercontent.com/40102557/41190093-d25ac3b8-6bd8-11e8-938c-9d9f069d96b5.jpg)
![2018-06-09 11_31_09-46 38 234 212 - remotedesktopverbindung](https://user-images.githubusercontent.com/40102557/41190094-d27704ce-6bd8-11e8-9a05-0c3cbc80e182.jpg)
![2018-06-09 11_32_30-46 38 234 212 - remotedesktopverbindung](https://user-images.githubusercontent.com/40102557/41190095-d28fc6b2-6bd8-11e8-896b-f0ace827b404.jpg)

**Comment by NiklasEi** [comment]
Found the problem. My distribution module was still depending on 2.1.2. I'll upload the new file on Spigot in a minute.
