### ISSUE TITLE
Press esc in the game and the plugin not restore inventory

### ISSUE THREAD

**Issue by andris155** [NiklasEi/gamebox#51]
https://www.youtube.com/watch?v=2afGcHguN_Q

GameBox 2.2.1
Paper 1.12.2

**Comment by NiklasEi** [comment]
Thank you for the report.
In the video you seem to be in creative mode. Can you also replicate that bug in survival?

**Comment by andris155** [comment]
This video created in survival mode.

**Comment by andris155** [comment]
Item pick up sometimes not work after playing Gamebox.

**Comment by andris155** [comment]
Find this error.
```
[16:48:26] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to GameBox v2.2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1533]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:943) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1765) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSkull.setOwner(CraftMetaSkull.java:166) ~[patched_1.12.2.jar:git-Paper-1533]
	at me.nikl.gamebox.utility.ItemStackUtility.getPlayerHead(ItemStackUtility.java:103) ~[?:?]
	at me.nikl.gamebox.inventory.gui.game.TopListPage.update(TopListPage.java:69) ~[?:?]
	at me.nikl.gamebox.data.toplist.TopList.updateUsers(TopList.java:70) ~[?:?]
	at me.nikl.gamebox.data.toplist.TopList.update(TopList.java:31) ~[?:?]
	at me.nikl.gamebox.data.database.DataBase.updateCachedTopList(DataBase.java:69) ~[?:?]
	at me.nikl.gamebox.data.database.FileDB.addStatistics(FileDB.java:118) ~[?:?]
	at me.nikl.gamebox.games.cookieclicker.CCGameManager.saveStatistics(CCGameManager.java:151) ~[?:?]
	at me.nikl.gamebox.games.cookieclicker.CCGame.onGameEnd(CCGame.java:334) ~[?:?]
	at me.nikl.gamebox.games.cookieclicker.CCGameManager.removeFromGame(CCGameManager.java:85) ~[?:?]
	at me.nikl.gamebox.games.cookieclicker.CCGameManager.onInventoryClose(CCGameManager.java:54) ~[?:?]
	at me.nikl.gamebox.PluginManager.onInvClose(PluginManager.java:296) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor378.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1533]
	... 17 more
```

**Comment by andris155** [comment]
```
[13:36:57] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to GameBox v2.2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1533]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:943) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:975) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:405) ~[patched_1.12.2.jar:git-Paper-1533]
	at me.nikl.gamebox.PluginManager.onInvClick(PluginManager.java:262) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor376.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1533]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1985) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.nikl.gamebox.games.cookieclicker.buildings.Building.getCount(Building.java:94) ~[?:?]
	at me.nikl.gamebox.games.cookieclicker.CCGame.onGameEnd(CCGame.java:328) ~[?:?]
	at me.nikl.gamebox.games.cookieclicker.CCGameManager.removeFromGame(CCGameManager.java:85) ~[?:?]
	at me.nikl.gamebox.games.cookieclicker.CCGameManager.onInventoryClose(CCGameManager.java:54) ~[?:?]
	at me.nikl.gamebox.PluginManager.onInvClose(PluginManager.java:296) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor378.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1533]
	... 26 more
```

**Comment by andris155** [comment]
I reseted data.yml fixed this.

**Comment by NiklasEi** [comment]
Yes, your first stacktrace looks like a name from the datafile was empty, whick led to a problem when loading a skull. I will add a check for that to prevent the errors.
